name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome and thank you for taking time out on creating this issue.'
        pr-message: 'Thank you for opening this Pull Request please hang tight, this PR will be reviewed and Merged ASAP, if there is no action on it in 7 days, please [reach me out](https://umairjibran.me)'
